### ISSUE TITLE
Use ARL policy as a starting point for code.mil

### ISSUE THREAD

**Issue by fulldecent** [deptofdefense/code.mil#85]
Much of the discussion here to date has been around licensing. There are many other practical considerations about open sourcing.

I am interpreting the scope of this project to include everything DoD project managers need to open source a project. Therefore those practical considerations are in scope.

I am working on PR #92 to start a document for those items.

DDS employees are welcome to call me at 267-738-4201. I want to make sure I am taking this is a direction you approve. It will be very helpful for me to understand the nuances of what contributions you are likely to accept.

# Work plan
- [x] Copy ARL policy to this repository on the `gh-pages` branch
   - [x] Note / cite that origin is ARL
   - [x] Update style as necessary (ARL uses title case for headings, I will use sentence case for headings as per https://standards.usa.gov/design-principles/)
- [x] Turn it into a SIMPLE web page that can be hosted at code.mil
  - [x] Use styling & templates per https://standards.usa.gov/page-templates/ from 18F
  - [x] Mention DRAFT/DISCUSSION status of the document
  - [x] Use Jekyll to convert markdown to html
- [x] Replace all mentions of Army Research Lab with DoD
- [x] Replace tone of document from "This is official ARL policy" to "DDS recommends you do this"
- [x] Offer DDS assistance to other DoD agencies in implementing these recommendations
- [x] Add links to other US Federal Government policies on publishing source code
  - ARL policy
  - https://code.gov/#/policy-guide/docs/overview/introduction 
  - https://github.com/18F/open-source-policy
- [x] Update vague references to "DoD Legal" to be "your agency's legal department" and similar.
- [x] Change RFC 2119 wording "MUST", "SHOULD", ... (which is appropriate for policy) to "should" and other language that is appropriate for a recommendation
- [x] Check all links, footnote references and glossary entries
- [x] Reword any language that appears like Defense Digital Service is speaking on behalf of DoD, because they're not
- [x] Clearly describe the role of the Defense Digital Service in supporting the DoD in the summary
- [x] Include Defense Digital Service contact information and specific points of contact for this project

# Acceptance plan

- [ ] DDS decides that PR #92 is good progress towards a draft and that this is what we should be focusing on
- [ ] DDS merges #92 into `gh-pages` branch (note: this will update code.mil, note: there are appropriate draft notice warnings on #92 to support this merge)

**Comment by ckaran** [comment]
@fulldecent We've worked on some of these issues already.  Take a look at [ARL's policy](https://github.com/USArmyResearchLab/ARL-Open-Source-Guidance-and-Instructions).

**Comment by fulldecent** [comment]
@ckaran ARL policy is great. Perhaps this can be made generic (s/ARL/DOD/) in a few places for the entire DoD audience and published at code.mil. I can help with this.

**Comment by ckaran** [comment]
@fulldecent  Sounds good!  Fork it and have at!  That said, I'm not going to pull the changes into the `master` branch;  the reason is that the policy you see **is** ARL's official policy; it is not a reflection of some other document.  If I pull in requests to the `master`, then I've changed official policy, and I need the Director's approval to do so.

That said, I'm open to a long-standing branch that hosts what you want;  if you fork it and make the changes, can you send me a pull request for some other sensibly named branch?

**Comment by shawoods** [comment]
@fulldecent We would be very interested in your thoughts about the practical implications for project managers. We'd welcome a PR for this repo with a document starting that discussion.

**Comment by ckaran** [comment]
@shawoods Take a look at ARL's stuff, and jump in where you want to.  I expect that there will be significant work on the `develop` branch shortly.

**Comment by fulldecent** [comment]
I have also jumped in on the ARL repo.

@shawoods thanks for the invitation to make a starting point here. Here is what I will do:

- [ ] Copy ARL policy to this repository on the `gh-pages` branch
- [ ] Turn it into a SIMPLE web page because I think the end point here will be a web page hosted at code.mil
- [ ] This will use styling per https://standards.usa.gov/page-templates/ from 18F
- [ ] Replace all mentions of Army Research Lab with DoD
- [ ] Replace tone of document from "This is official ARL policy" to "DDS recommends you do this"
- [ ] Offer DDS assistance to other DoD agencies in implementing these recommendations (since I believe this is your goal)
- [ ] Add links to other US Federal Government policies on publishing source code
  - ARL policy
  - https://code.gov/#/policy-guide/docs/overview/introduction 
- [ ] Create a pull request
- [ ] Identify gaps in this implementation and how they can be addressed before end of March

My goal here is to take this project from planning plan towards the finish line. Anyone in DDS is welcome to give me a call at 267-738-4201. I'll want to ask a little more about your goals here. This will help ensure that I am working in the right direction towards something that will be useful.

**Comment by ckaran** [comment]
@fulldecent @shawoods Would you be willing to make a note that it was forked from ARL's policy?  Citation count/fame is part of how ARL keeps its funding...

**Comment by fulldecent** [comment]
@ckaran of course, noted in project plan above

**Comment by fulldecent** [comment]
Please see pull request #92, this is a DECENT start of wholesale stealing ARL's brilliant policy and turning it into a recommendation on behalf of DDS for all of DoD.

This PR updates code.mil and it (implicitly) describes the scope of this (code.mil) project. Basically it is a rewrite.

Working on this discussion is fun, but I want to do what is necessary to get this PR approved and accepted. This will validate that I have understand this project's mission and that other people should spend their valuable time on improving these efforts towards the final product as per the roadmap I have laid out above and in the checklist on the index.md in the project.

**Comment by ckaran** [comment]
Since all of this discussion may be a Federal Record, deleting `master` may not be a good idea; at the very least, move what you've got to a different branch that you keep around for posterity.

**Comment by fulldecent** [comment]
@ckaran This is addressed in an updated Acceptance Plan above

**Comment by ckaran** [comment]
@fulldecent Good, thank you!

**Comment by fulldecent** [comment]
I have made progress on #92 and implemented the work plan above.

We now have a candidate website to replace code.mil. You can test this website by accessing my pull request, running `jekyll serve` and viewing from your web browser. But it is basically the same as just reading the markdown files.

![screen shot 2017-03-01 at 4 02 21 pm](https://cloud.githubusercontent.com/assets/382183/23481193/935a8b3e-fe98-11e6-8460-8a204e439a3a.png)

----

Dear DDS members @shawoods @BrandonBouier @tomberek @erincd @nickjs   @reinastaley  @spoon16 @ExoUNX, US government contributors @konklone LNL @IanLee1521 @shawnbot, and other contributors @crbinz @nschonni @rthbound,

Would you please help review this pull request. It's not perfect. But I want to know if you support this as a step forward for the code.mil experiment. 

If DDS members support this, please let me know the minimum changes required for this to be accepted. Once accepted, we can close this issue and then focus all efforts together on moving forward from this new beginning.

**Comment by BrandonBouier** [comment]
@fulldecent Thanks for PR #92! We really appreciate your enthusiasm and contribution to Code.mil. We are super focused on finalizing CONTRIBUTING.md, FAQ.md, and README.md and then releasing a few of our software projects.  

Just wanted to let you know it might be a little while before we tackle this PR in earnest.  As far as developing a website that is definitely on our radar, but we have to do some more legwork with other folks int he government.  We don’t want to discourage your efforts, but the website work might be jumping the gun a little as we’re still developing our design strategy and gathering information, in addition to finalizing this work and preparing code for release.

**Comment by fulldecent** [comment]
The "website" part is just one file, https://github.com/fulldecent/code.mil/blob/gh-pages-arl-rewrite/_layouts/page.html, that is lifted from 18F's template and it translates markdown to HTML. That's not the important part.

The important review is

* Does this project goal and other statements at https://github.com/fulldecent/code.mil/blob/gh-pages-arl-rewrite/index.md accurately portray DSS's goal and role in this project?
* Does ARL's policy, translated into a DSS recommendation at https://github.com/fulldecent/code.mil/blob/gh-pages-arl-rewrite/implementation-guide.md successfully implement the goals of CONTRIBUTING.md, FAQ.md and README.md you are working on?

**Comment by fulldecent** [comment]
#92 is merged, closing this issue. Discussion continues at #126 which gets this code published to the world wide web.
